# gamma: 0.99
# seed: 42
# tensorboard_log_dir: "log_dir"
# policy_name: "MlpPolicy"
# verbose: 1
# steps: 1000
# load_model: 0  
# save_every_steps: 1000
# learning_rate: 0.0003
# # Replay Buffer Size. Ensure that it is greater than number of timesteps you want to assign human reward credit for.
# buffer_size: 3072
# learning_starts: 32
# batch_size: 32
# tau: 0.01
# train_freq: 1
# gradient_steps: 1
# human_data_save_path: "human_study/participant_1"
# trained_model: "trained-models/LunarLanderContinuous-v2.zip"

gamma: 0.99
seed: 33
tensorboard_log_dir: "log_dir/sawyer_active_task2"
policy_name: "ActiveMlpPolicyBallBasket"
verbose: 1
steps: 2500
load_model: 0  
save_every_steps: 100
learning_rate: 0.00075
# Replay Buffer Size. Ensure that it is greater than number of timesteps you want to assign human reward credit for.
#1000000
buffer_size: 1000000
learning_starts: 0
batch_size: 100
tau: 0.01
train_freq: 1
gradient_steps: 8
human_data_save_path: "robot_task2_data/activeTAMER/participant_1"
trained_model: "models/robot_task2/robot_active/well_trained_model/ActiveTamerRLSACOptimBallBasket_1200.pt"
percent_feedback: 1
load_model: "models/trained/ActiveTamerRLSACOptimBallBasket_100.pt"