from pynput import keyboard, mouse

# Behavior Robot Corrective Action:
# order: torso - x, y, z, roll, pitch, yaw
#        head
#        left hand
#        right hand
#        gripper
behavior_robot = {
    keyboard.KeyCode.from_char("a"): [
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
    ],  # +y
    keyboard.KeyCode.from_char("s"): [
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],  # -x
    keyboard.KeyCode.from_char("z"): [
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
    ],  # +z
    keyboard.KeyCode.from_char("w"): [
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],  # +x
    keyboard.KeyCode.from_char("x"): [
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
    ],  # -z
    keyboard.KeyCode.from_char("d"): [
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
    ],  # -y
}

# Fetch Robot Corrective Action:
# order: torso - x, y, z, roll, pitch, yaw
#        head
#        left hand
#        right hand
#        gripper
fetch_robot = {
    keyboard.KeyCode.from_char("a"): [
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],  # +y
    keyboard.KeyCode.from_char("s"): [
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ],  # -x
    keyboard.KeyCode.from_char("z"): [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],  # +z
    keyboard.KeyCode.from_char("w"): [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # +x
    keyboard.KeyCode.from_char("x"): [0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],  # -z
    keyboard.KeyCode.from_char("d"): [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # -y
}
