gamma: 0.99
seed: 42
tensorboard_log_dir: "log_dir"
policy_name: "MlpPolicy"
verbose: 1
steps: 200000
load_model: 0  
save_every_steps: 50000
learning_rate: 0.00073

# Replay Buffer Size. Ensure that it is greater than number of timesteps you want to assign human reward credit for.
#1000000
buffer_size: 1000000
learning_starts: 10000
batch_size: 256
tau: 0.01
train_freq: 1
gradient_steps: 1
