hidden_dim: 256
num_layers: 2
gamma: 0.99
seed: 42
epochs: 50
tensorboard_log_dir: "log_dir"
policy_name: "MultiInputPolicy"
verbose: 1
steps: 1000
load_model: 0  
save_every_steps: 1000
learning_rate: 0.0003

# Replay Buffer Size. Ensure that it is greater than number of timesteps you want to assign human reward credit for.
buffer_size: 3072
learning_starts: 32
batch_size: 32
tau: 0.005
train_freq: 8
gradient_steps: 1
human_data_save_path: "human_study/participant_1"
trained_model: "trained-models/LunarLanderContinuous-v2.zip"