# gamma: 0.99
# seed: 42
# tensorboard_log_dir: "log_dir"
# policy_name: "MlpPolicy"
# verbose: 1
# steps: 1000
# load_model: 0  
# save_every_steps: 1000
# learning_rate: 0.0003
# # Replay Buffer Size. Ensure that it is greater than number of timesteps you want to assign human reward credit for.
# buffer_size: 3072
# learning_starts: 32
# batch_size: 32
# tau: 0.01
# train_freq: 1
# gradient_steps: 1
# human_data_save_path: "human_study/participant_1"
# trained_model: "trained-models/LunarLanderContinuous-v2.zip"

gamma: 0.99
seed: 42
tensorboard_log_dir: "log_dir"
policy_name: "ActiveMlpPolicyBallBasket"
verbose: 1
steps: 150000
load_model: 0  
save_every_steps: 50000
learning_rate: 0.00075
# Replay Buffer Size. Ensure that it is greater than number of timesteps you want to assign human reward credit for.
#1000000
buffer_size: 1000000
learning_starts: 0
batch_size: 512
tau: 0.01
train_freq: 1
gradient_steps: 8
human_data_save_path: "human_study/participant_1"
trained_model: "trained-models/BallReaching.pt"
percent_feedback: 1
# load_model: "ActiveTamerRLSACOptim_2.pt"